version: 0.1

phases:
    install:
         commands:
            - npm install -g serverless -y
            - npm install serverless-plugin-split-stacks -y
    build:
         commands:
            - serverless package
            - cp .serverless/cloudformation-template-update-stack.json .serverless/template-export.json 
            - aws s3 cp ./.serverless s3://testheadlight/template/ --include '/*.json' --exclude '/*' --recursive
artifacts:       
  type: zip
  files:
    - .serverless/*          
      
