version: 0.1

phases:
    install:
         commands:
            - npm install -g serverless --save
    post_build:
         commands:
            - serverless deploy --region eu-west-1 --verbose        