version: 0.1

phases:
    install:
         commands:
            - npm install -g serverless -y
            - npm install serverless-plugin-split-stacks -y
            - npm install --global jq-cli-wrapper
    build:
         commands:
            - serverless package
            - cp .serverless/cloudformation-template-update-stack.json .serverless/template-export.json 
artifacts:       
  type: zip
  files:
    - .serverless/*          
      
