version: 0.1

phases:
    install:
         commands:
            - npm install jq -y
            - npm install -g serverless -y
            - npm install serverless-plugin-split-stacks -y
    build:
         commands:
            - serverless package
            - bash upload.sh
            - cp .serverless/cloudformation-template-update-stack.json .serverless/template-export.json 
artifacts:       
  type: zip
  files:
    - .serverless/*          
      
