version: 0.1

phases:
    install:
         commands:
            - npm install -g serverless 
            - npm install serverless-plugin-split-stacks 
    build:
         commands:
            - serverless package
            - ./upload.sh
            - cp .serverless/cloudformation-template-update-stack.json .serverless/template-export.json 
artifacts:       
  type: zip
  files:
    - .serverless/*          
      